import "./globals.css";
import type { Metadata } from "next";
import Navbar from "./components/Navbar";
import { Inter } from "next/font/google";
import {ChatAppProvider} from './context/ChatAppContext';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ChatAppProvider>
        <body suppressHydrationWarning={true} className={inter.className}>
          <Navbar />
          {children}
          </body>
      </ChatAppProvider>
    </html>
  );
}
